# Travis CI configuration file

language: ruby

rvm:
  - 2.2.0

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database mayday_test;' -U postgres
  - cp config/database.yml.example config/database.yml
