# Fig configuration file for Mayday-2.0 app

web:
  build: .
  command: rails server -b 0.0.0.0
  volumes:
    - .:/usr/src/app
  ports:
    - "3000:3000"
  links:
    - db
    - redis
  env_file:
    - .env
  environment:
    - DATABASE_URL=postgres://postgres@db:5432/postgres
    - REDIS_URL=redis://redis@redis:6379/

worker:
  image: mayday20backend_web:latest
  command: bundle exec sidekiq -c 10
  volumes:
    - .:/usr/src/app
  links:
    - redis
  env_file:
    - .env
  environment:
    - REDIS_PROVIDER=REDIS_URL
    - REDIS_URL=redis://redis@redis:6379/

db:
  image: postgres:9.4

redis:
  image: redis:2.6
